AllCops:
  TargetRubyVersion: 3.4.4
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 40
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ClassLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Documentation:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: true

Metrics/AbcSize:
  Max: 25
